config/routes.rb
Rails.application.routes.draw do
require 'sidekiq/web'

   resources :videos 
   root "videos#index"
   mount Sidekiq::Web => '/sidekiq'

end

app/models/video.rb
class Video < ActiveRecord::Base
	extend FriendlyId
#friendly_id :title, use: :slugged
friendly_id :title, use: [:slugged, :finders,:history]
mount_uploader :media, VideoUploader
validates :title, :description, :presence => true 

def video_screenshot
	screenshot_path = Rails.root+"/app/assets/images/screenshots/#{self.slug}_#{self.id}.jpg"
	if FileTest.exists?(screenshot_path)
		@screenshot = screenshot_path
	else
		video_file = FFMPEG::Movie.new("#{Rails.root}/public"+self.video.url(:mp4))
		@screenshot = video_file.screenshot("#{screenshot_path}")
	end
end

process_in_background :media

def self.get_other_videos(video_id)
videos = Video.where.not(id: video_id) rescue nil
return videos
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :set_video, :except => [:index, :new, :create]

	def index
		@videos = Video.all
	end

	def new
		@video = Video.new
	end

	def edit
	end

	def show
		@videos = Video.get_other_videos(@video.id)
	end

	def create
		@video = Video.new(video_params)
		if @video.save
			  gflash success: "video was successfully created."
			redirect_to videos_path
		else
			gflash :now, error: @video.errors.full_messages.join("<br/>").html_safe
			render "new"
		end
	end

	def update
		if @video.update(video_params)
			redirect_to videos_path
		else
			render "edit"
		end
	end

	def destroy
		@video.destroy
		redirect_to videos_path
	end

	private 

	def set_video
		@video = Video.friendly.find(params[:id])
	end

	def video_params
	#	params.require(:video).permit!
		params.require(:video).permit(:title, :description, :media, :media_cache)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Videohtml</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
    <%= gflash %>
</body>
</html>

app/views/videos/_form.html.erb
<%= form_for @video, :html => {:multipart => true} do |f| %> 

<div class="form-field">
<%= f.label :title %>
<%= f.text_field :title %> 
</div>

<div class="form-field">
<%= f.label :description %>
<%= f.text_field :description %> 
</div>

<div class="form-group">
<label for="InputFile">Upload Video</label>
<%= f.file_field :media %>
<%= f.hidden_field :media_cache %>
<p class="help-block"></p>
</div>
<%= f.submit "Save", :class => "btn btn-default" %> 
<%= link_to 'Cancel', videos_path, :class => "btn btn-danger" %>


<%end%>

app/views/videos/edit.html.erb
<h1> Edit Video</h1>
<%= render "form"%>

app/views/videos/index.html.erb
<%@videos.each do |v| %>
<div id="page-wrapper">
<h2> Title </h2>
<%= v.title %>
</div>
<div id="page-wrapper">
<h2> Description </h2>
<%= v.description %>
</div>
<video id="video_1" class="video-js vjs-default-skin"
controls preload="none" width="640" height="264"
data-setup="{}">
<source src="<%=video_tag v.media%>" />
</video>
<br/>

<div id="page-wrapper">
<h2>  </h2>
<%= link_to "Edit", edit_video_path(v), :class => "btn btn-primary" %>
<%= link_to "Show", video_path(v), :class => "btn btn-primary" %>
<%= link_to "Delete", video_path(v),:method => :delete,:data =>{:confirm => "Are you sure"}, 
:class => "btn btn-danger" %>
</div>

<%end%>

<%= link_to "New", new_video_path %>  

<script>
videojs.options.flash.swf = "#{Rails.root}/video-js.swf";
</script>

app/views/videos/new.html.erb
<h1> New Video</h1>
<%= render "form"%>

app/views/videos/show.html.erb
<div class="row">
<div class="col-lg-8">
<h3><%= @video.title %></h3>
<video id="video_1" class="video-js vjs-default-skin"
controls preload="none" width="640" height="264"
data-setup="{}">
<source src="<%=@video.media.url(:mp4)%>" type='video/mp4' />
</video>
<br/>
<p><%= @video.description %></p>
</div>
</div>

<%= link_to "Back", videos_path, :class => "btn btn-primary"%>